using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NDesk.Options;

using Isas.Shared;
using CanvasCommon;

namespace CanvasSmooth
{
    class Program
    {
        static void Main(string[] args)
        {
            CanvasCommon.Utilities.LogCommandLine(args);
            IFileLocation inputFile = null;
            IFileLocation outputFile = null;
            uint maxHalfWindowSize = 0; // window size: 2 * "half window size" + 1
            bool needHelp = false;

            OptionSet p = new OptionSet()
            {
                { "i|infile=",            "input file - usually generated by CanvasClean",      v => inputFile = new FileLocation(v) },
                { "o|outfile=",           "text file to output containing smoothed bins",      v => outputFile = new FileLocation(v) },
                { "w|maxHalfWindowSize=", "maximum half window size", v => maxHalfWindowSize = uint.Parse(v) }
            };


        }
    }
}
