using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Illumina.Common;
using Illumina.Common.FileSystem;
using Newtonsoft.Json;

namespace CanvasPartition
{
    class CanvasPartition
    {
        static void ShowHelp(OptionSet p)
        {
            Console.WriteLine("Usage: CanvasPartition.exe [OPTIONS]+");
            Console.WriteLine("Divide bins into consistent intervals based on their counts");
            Console.WriteLine();
            Console.WriteLine("Options:");
            p.WriteOptionDescriptions(Console.Out);
        }

        static int Main(string[] args)
        {
            CanvasCommon.Utilities.LogCommandLine(args);
            List<string> cleanedFiles = new List<string>();
            List<string> outPartitionedFiles = new List<string>();
            List<string> vafFiles = new List<string>();
            bool needHelp = false;
            bool isGermline = false;
            string filterBedFile = null;
            string referenceFolder = null;
            string commonCNVsbedPath = null;
            string coverageMetricsFile = null;
            SegmentSplitUndo undoMethod = SegmentSplitUndo.None;
            SegmentationInput.SegmentationMethod partitionMethod = SegmentationInput.SegmentationMethod.Wavelets;
            string parameterconfigPath = Path.Combine(Isas.Framework.Utilities.Utilities.GetAssemblyFolder(typeof(CanvasPartition)), "CanvasPartitionParameters.json");


            OptionSet p = new OptionSet()
            {
                { "i|infile=", "input file - usually generated by CanvasClean", v => cleanedFiles.Add(v) },
                { "v|vaffile=", "variant frequencyfiles - usually generated by CanvasSNV", v => vafFiles.Add(v) },
                { "o|outfile=", "text file to output", v => outPartitionedFiles.Add(v) },
                { "m|method=", "segmentation method (Wavelets/CBS). Default: " + partitionMethod, v => partitionMethod = (SegmentationInput.SegmentationMethod)Enum.Parse(typeof(SegmentationInput.SegmentationMethod), v) },
                { "r|reference=", "folder that contains both genome.fa and GenomeSize.xml", v => referenceFolder = v},
                { "s|split=", "CBS split method (None/Prune/SDUndo). Default: " + undoMethod, v => undoMethod = (SegmentSplitUndo)Enum.Parse(typeof(SegmentSplitUndo), v) },
                { "b|bedfile=", "bed file to exclude (don't span these intervals)", v => filterBedFile = v },
                { "c|commoncnvs=", "bed file with common CNVs (always include these intervals into segmentation results)", v => commonCNVsbedPath = v },             
                { "g|germline", "flag indicating that input file represents germline genome", v => isGermline = v != null },
                { "f|coverageMetrics=", "text file with coverage metrics (optional)", v => coverageMetricsFile = v},                
                { "config=", "parameter configuration path (default {parameterconfigPath})", v => parameterconfigPath = v},
                { "h|help", "show this message and exit", v => needHelp = v != null }
            };

            List<string> extraArgs = p.Parse(args);

            if (needHelp)
            {
                ShowHelp(p);
                return 0;
            }

            if (!cleanedFiles.Any() || !outPartitionedFiles.Any() || referenceFolder == null)
            {
                ShowHelp(p);
                return 0;
            }

            if (cleanedFiles.Any(inFile => !File.Exists(inFile)))
            {
                Console.WriteLine("CanvasPartition.exe: File {0} does not exist! Exiting.", cleanedFiles);
                return 1;
            }

            if (!string.IsNullOrEmpty(filterBedFile) && !File.Exists(filterBedFile))
            {
                Console.WriteLine("CanvasPartition.exe: File {0} does not exist! Exiting.", filterBedFile);
                return 1;
            }

            if (!string.IsNullOrEmpty(coverageMetricsFile) && !File.Exists(coverageMetricsFile))
            {
                Console.WriteLine("CanvasPartition.exe: File {0} does not exist! Exiting.", coverageMetricsFile);
                return 1;
            }


            if (partitionMethod != SegmentationInput.SegmentationMethod.HMM && outPartitionedFiles.Count > 1)
            {
                Console.WriteLine("CanvasPartition.exe: SegmentationMethod.HMM only works for MultiSample SPW worlfow, " +
                                  "please provide multiple -o arguments");
                return 1;
            }

            if (partitionMethod == SegmentationInput.SegmentationMethod.HMM && cleanedFiles.Count == 1)
            {
                Console.WriteLine("CanvasPartition.exe: method=HMM option only works when more than one input files (-i) are provided");
                return 1;
            }

            if (!File.Exists(parameterconfigPath))
            {
                Console.WriteLine($"CanvasPedigreeCaller.exe: File {parameterconfigPath} does not exist! Exiting.");
                return 1;
            }

            var parameterconfigFile = new FileLocation(parameterconfigPath);
            var canvasPartitionParameters = Deserialize<CanvasPartitionParameters>(parameterconfigFile);

            var segmentationInputs = vafFiles.Count > 0 && vafFiles.Count == cleanedFiles.Count ? 
                cleanedFiles.Zip(vafFiles, (inFile, vafFile) => new SegmentationInput(inFile, vafFile, filterBedFile, 
                canvasPartitionParameters.MaxInterBinDistInSegment, referenceFolder, coverageMetricsFile)).ToList():
                cleanedFiles.Select(inFile => new SegmentationInput(inFile, null, filterBedFile, canvasPartitionParameters.MaxInterBinDistInSegment, 
                referenceFolder, coverageMetricsFile)).ToList();   
            SegmentationInput.GenomeSegmentationResults segmentationResults;
            switch (partitionMethod)
            {
                default:// use Wavelets if CBS is not selected       
                    Console.WriteLine("{0} Running Wavelet Partitioning", DateTime.Now);
                    var waveletsRunner = new WaveletsRunner(new WaveletsRunner.WaveletsRunnerParams(isGermline, commonCNVsbedPath, madFactor: 
                        canvasPartitionParameters.MadFactor, thresholdLowerMaf: canvasPartitionParameters.ThresholdLowerMaf, verbose: 2));
                    segmentationResults = new SegmentationInput.GenomeSegmentationResults(waveletsRunner.Run(segmentationInputs.Single()));
                    segmentationInputs.Single().WriteCanvasPartitionResults(outPartitionedFiles.Single(), segmentationResults);
                    break;
                case SegmentationInput.SegmentationMethod.CBS:
                    Console.WriteLine("{0} Running CBS Partitioning", DateTime.Now);
                    var cbsRunner = new CBSRunner(canvasPartitionParameters.MaxInterBinDistInSegment, undoMethod, canvasPartitionParameters.CBSalpha);
                    segmentationResults = new SegmentationInput.GenomeSegmentationResults(cbsRunner.Run(segmentationInputs.Single(), verbose: 2));
                    segmentationInputs.Single().WriteCanvasPartitionResults(outPartitionedFiles.Single(), segmentationResults);
                    break;
                case SegmentationInput.SegmentationMethod.HMM:
                    Console.WriteLine("{0} Running HMM Partitioning", DateTime.Now);
                    var hiddenMarkovModelsRunner = new HiddenMarkovModelsRunner(commonCNVsbedPath, cleanedFiles.Count);
                    segmentationResults = new SegmentationInput.GenomeSegmentationResults(hiddenMarkovModelsRunner.Run(segmentationInputs));
                    for (int i = 0; i < segmentationInputs.Count; i++)
                        segmentationInputs[i].WriteCanvasPartitionResults(outPartitionedFiles[i], segmentationResults);
                    break;
            }
            Console.WriteLine("{0} CanvasPartition results written out", DateTime.Now);
            return 0;
        }
        private static T Deserialize<T>(IFileLocation path)
        {
            using (StreamReader reader = path.OpenText())
                return JsonConvert.DeserializeObject<T>(reader.ReadToEnd());
        }
    }
}
