using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Illumina.Common;

namespace CanvasPartition
{
    class CanvasPartition
    {
        static void ShowHelp(OptionSet p)
        {
            Console.WriteLine("Usage: CanvasPartition.exe [OPTIONS]+");
            Console.WriteLine("Divide bins into consistent intervals based on their counts");
            Console.WriteLine();
            Console.WriteLine("Options:");
            p.WriteOptionDescriptions(Console.Out);
        }

        static int Main(string[] args)
        {
            CanvasCommon.Utilities.LogCommandLine(args);
            List<string> cleanedFiles = new List<string>();
            List<string> outPartitionedFiles = new List<string>();
            List<string> vafFiles = new List<string>();
            bool needHelp = false;
            bool isGermline = false;
            string filterBedFile = null;
            string referenceFolder = null;
            string commonCNVsbedPath = null;
            double alpha = CBSRunner.DefaultAlpha;
            double madFactor = WaveletsRunner.DefaultMadFactor;
            SegmentSplitUndo undoMethod = SegmentSplitUndo.None;
            SegmentationInput.SegmentationMethod partitionMethod = SegmentationInput.SegmentationMethod.Wavelets;
            int maxInterBinDistInSegment = 1000000;
            OptionSet p = new OptionSet()
            {
                { "i|infile=", "input file - usually generated by CanvasClean", v => cleanedFiles.Add(v) },
                { "v|vaffile=", "variant frequencyfiles - usually generated by CanvasSNV", v => vafFiles.Add(v) },
                { "o|outfile=", "text file to output", v => outPartitionedFiles.Add(v) },
                { "h|help", "show this message and exit", v => needHelp = v != null },
                { "m|method=", "segmentation method (Wavelets/CBS). Default: " + partitionMethod, v => partitionMethod = (SegmentationInput.SegmentationMethod)Enum.Parse(typeof(SegmentationInput.SegmentationMethod), v) },
                {"r|reference=", "folder that contains both genome.fa and GenomeSize.xml", v => referenceFolder = v},
                { "a|alpha=", "alpha parameter to CBS. Default: " + alpha, v => alpha = float.Parse(v) },
                { "s|split=", "CBS split method (None/Prune/SDUndo). Default: " + undoMethod, v => undoMethod = (SegmentSplitUndo)Enum.Parse(typeof(SegmentSplitUndo), v) },
                { "f|madFactor=", "MAD factor to Wavelets. Default: " + madFactor, v => madFactor = float.Parse(v) },
                { "b|bedfile=", "bed file to exclude (don't span these intervals)", v => filterBedFile = v },
                { "c|commoncnvs=", "bed file with common CNVs (always include these intervals into segmentation results)", v => commonCNVsbedPath = v },             
                { "g|germline", "flag indicating that input file represents germline genome", v => isGermline = v != null },
                { "d|maxInterBinDistInSegment=", "the maximum distance between adjacent bins in a segment (negative numbers turn off splitting segments after segmentation). Default: " + maxInterBinDistInSegment, v => maxInterBinDistInSegment = int.Parse(v) },
            };

            List<string> extraArgs = p.Parse(args);

            if (needHelp)
            {
                ShowHelp(p);
                return 0;
            }

            if (!cleanedFiles.Any() || !outPartitionedFiles.Any() || referenceFolder == null)
            {
                ShowHelp(p);
                return 0;
            }

            if (cleanedFiles.Any(inFile => !File.Exists(inFile)))
            {
                Console.WriteLine("CanvasPartition.exe: File {0} does not exist! Exiting.", cleanedFiles);
                return 1;
            }

            if (!string.IsNullOrEmpty(filterBedFile) && !File.Exists(filterBedFile))
            {
                Console.WriteLine("CanvasPartition.exe: File {0} does not exist! Exiting.", filterBedFile);
                return 1;
            }

            if (partitionMethod != SegmentationInput.SegmentationMethod.HMM && outPartitionedFiles.Count > 1)
            {
                Console.WriteLine("CanvasPartition.exe: SegmentationMethod.HMM only works for MultiSample SPW worlfow, " +
                                  "please provide multiple -o arguments");
                return 1;
            }

            if (partitionMethod == SegmentationInput.SegmentationMethod.HMM && cleanedFiles.Count == 1)
            {
                Console.WriteLine("CanvasPartition.exe: method=HMM option only works when more than one input files (-i) are provided");
                return 1;
            }

            var segmentationInputs = cleanedFiles.Zip(vafFiles, (inFile, vafFile) => new SegmentationInput(inFile, vafFile, filterBedFile, maxInterBinDistInSegment, referenceFolder)).ToList();          
            SegmentationInput.GenomeSegmentationResults segmentationResults;
            switch (partitionMethod)
            {
                default:// use Wavelets if CBS is not selected       
                    Console.WriteLine("{0} Running Wavelet Partitioning", DateTime.Now);
                    var waveletsRunner = new WaveletsRunner(new WaveletsRunner.WaveletsRunnerParams(isGermline, commonCNVsbedPath, madFactor: madFactor, verbose: 2));
                    segmentationResults = new SegmentationInput.GenomeSegmentationResults(waveletsRunner.Run(segmentationInputs.Single()));
                    segmentationInputs.Single().WriteCanvasPartitionResults(outPartitionedFiles.Single(), segmentationResults);
                    break;
                case SegmentationInput.SegmentationMethod.CBS:
                    Console.WriteLine("{0} Running CBS Partitioning", DateTime.Now);
                    var cbsRunner = new CBSRunner(maxInterBinDistInSegment, undoMethod, alpha);
                    segmentationResults = new SegmentationInput.GenomeSegmentationResults(cbsRunner.Run(segmentationInputs.Single(), verbose: 2));
                    segmentationInputs.Single().WriteCanvasPartitionResults(outPartitionedFiles.Single(), segmentationResults);
                    break;
                case SegmentationInput.SegmentationMethod.HMM:
                    Console.WriteLine("{0} Running HMM Partitioning", DateTime.Now);
                    var hiddenMarkovModelsRunner = new HiddenMarkovModelsRunner(commonCNVsbedPath, cleanedFiles.Count);
                    segmentationResults = new SegmentationInput.GenomeSegmentationResults(hiddenMarkovModelsRunner.Run(segmentationInputs));
                    for (int i = 0; i < segmentationInputs.Count; i++)
                        segmentationInputs[i].WriteCanvasPartitionResults(outPartitionedFiles[i], segmentationResults);
                    break;
            }
            Console.WriteLine("{0} CanvasPartition results written out", DateTime.Now);
            return 0;
        }
    }
}
